<?php 
$read = Mage::getSingleton('core/resource')->getConnection('core_read');
				$write = Mage::getSingleton('core/resource')->getConnection('core_write');

$logindetail= $read->fetchAll("select * from shipway  where shipway_id=1");
$couriermap= $read->fetchAll("select * from shipway_couriermapping ");
$customecouriermap= $read->fetchAll("select * from shipway_couriermapping where courier_type='custom' ");
/* echo '<pre>';
print_r($customecouriermap);
echo '</pre>'; */
if(count($logindetail)){

$shipway_loginid= $logindetail[0]['loginid'];
$shipway_licencekey= $logindetail[0]['licencekey'];
}
else{
$shipway_loginid= '';
$shipway_licencekey= '';
}
  
?>
<?php 
$options = array();
           $carrierInstances = Mage::getSingleton('shipping/config')->getAllCarriers( );
         //$carriers['custom'] = Mage::helper('sales')->__('Custom Value');
           foreach ($carrierInstances as $code => $carrier) {
              if ($carrier->isTrackingAvailable()) {
                 $carriers_title = $carrier->getConfigData('title');
				 $options[] = array('value' => $code, 'label' => $carriers_title );
               }
           }
	$url         = "http://shipway.in/api/getcarrier";
			$data_string = array(
				"username" => $shipway_loginid,
				"password" => $shipway_licencekey
			);
			
			$data_string = json_encode($data_string);
			$curl        = curl_init();
			curl_setopt($curl, CURLOPT_HTTPHEADER, array(
				'Content-Type:application/json'
			));
			curl_setopt($curl, CURLOPT_URL, $url);
			curl_setopt($curl, CURLOPT_POST, true);
			curl_setopt($curl, CURLOPT_POSTFIELDS, $data_string);
			curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
			curl_setopt($curl, CURLOPT_FOLLOWLOCATION, 1);
			curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);
			$output = curl_exec($curl);

			curl_close($curl);
			$output = (array)json_decode($output);
		
			?>

<form action="<?php echo $this->getFormAction().'key/'.$this->getFormKey(); ?>" method="POST">
<div class="content-header">
    <table cellspacing="0">
		<tbody>
			<tr>
				<td style="width:50%;"><h3 class="icon-head head-sales-order">Shipway Courier Mapping</h3></td>
				<td class="form-buttons"><button class="scalable" onclick="<?php echo $this->getFormAction(); ?>">Save Mapping</button></td>
			</tr>
		</tbody>
	</table>
</div>

<div class="grid">
<h2>Shipway Courier Mapping</h2> <br>
<input type="hidden" name="form_key" value="<?php echo $this->getFormKey(); ?>" />

<table style=" width: 40%; float: left;" id="myTable">
	<tr>
		<th>Courier Name</th><th>Shipway Courier</th>
	</tr>
	<?php foreach($options as $key1 => $value){ ?>
	<tr>
		<td><?php echo $options[$key1]['label']?></td>
		<td>
			<select name="shipway[<?php echo $options[$key1]['value']?>]">
				<option value="">Select courier</option>
				<?php foreach($output as $key => $carrier_name){?>
				<option value="<?php echo $key; ?>" <?php if($couriermap[$key1]['shipway_courierid']==$key){echo "selected";}?>><?php echo ucfirst($carrier_name);?></option>
				<?php } ?>
			</select>
		</td>
	</tr>
	<?php } ?>
	<?php foreach($customecouriermap as $key1 => $value){ ?>
	<tr>
		<td><input type="text"  name="shipway_customcourier_name[]" value="<?php echo $customecouriermap[$key1]['default_courier']?>"></td>
		<td>
			<select name="shipway_courier_id[]">
				<option value="">Select courier</option>
				<?php foreach($output as $key => $carrier_name){?>
				<option value="<?php echo $key; ?>" <?php if($customecouriermap[$key1]['shipway_courierid']==$key){echo "selected";}?>><?php echo ucfirst($carrier_name);?></option>
				<?php } ?>
			</select>
			</td>
	</tr>
	<?php } ?>
</table>
</div>
<div style="clear:both;"></div>
<div style="margin-top:20px; margin-left: 30%;"><input type="button" class="addCF" onclick="addcustomcourier();" value="Add Custom Courier" ></div>
</form>
<script>
function addcustomcourier(){

//$('#myTable').append('<tr><td>my data</td><td>more data</td></tr>');
var table = document.getElementById("myTable");

// Create an empty <tr> element and add it to the 1st position of the table:
var row = table.insertRow(-1);

// Insert new cells (<td> elements) at the 1st and 2nd position of the "new" <tr> element:
var cell1 = row.insertCell(0);
var cell2 = row.insertCell(1);

// Add some text to the new cells:
cell1.innerHTML = "<input type='text' placeholder='custom courier' name='shipway_customcourier_name[]'>";
var html="";
html+='<select name="shipway_courier_id[]">';
<?php foreach ($output as $key=> $carrier_name) { ?>
	html += '<option value="<?php echo $key; ?>"><?php echo ucfirst($carrier_name);?></option>';
    <?php } ?>
	html+='</select>';
cell2.innerHTML = html;
}

</script>


